### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by seantree** [phdphuc/mac-a-mal-cuckoo#1]
Hello,
I am using your repository but getting some errors, I just want to know is there any documentation available for this? So, that I can try to build by following the correct documentation.
.
Waiting for your positive reply.
.
Thanks & Regards
Seantree

**Comment by phdphuc** [comment]
Hi @seantree,

We are working on this at the moment. You also can take a look at [cuckoo-osx-analyzer ](https://github.com/rodionovd/cuckoo-osx-analyzer/wiki/Setting-up-the-environment) for environment setup. If there's anything I can help, feel free to [poke me](https://twitter.com/phd_phuc because I don't know why I haven't heard any notifications from Github on new issues.

Regards,
Pham.

**Comment by siftuser** [comment]
@phdphuc As suggested by you, tried following [this guide](https://github.com/rodionovd/cuckoo-osx-analyzer/wiki/Setting-up-the-environment) to setup mac-analysis. But seeing following error on step 3. 

`cuckoo@cuckoo-VirtualBox:~$ bash ./cuckoo-osx-analyzer/scripts/bootstrap_host.sh`
```VBoxManage: error: The host network interface named 'vboxnet0' could not be found
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component HostWrap, interface IHost, callee nsISupports
VBoxManage: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 231 of file VBoxManageHostonly.cpp
I can't setup traffic forwarding for your OS, sorry :(
```
Manually added host-only adapter `vboxnet0` network & ran the `bootstrap_host` script again
`cuckoo@cuckoo-VirtualBox:~$ bash ./cuckoo-osx-analyzer/scripts/bootstrap_host.sh`
```I can't setup traffic forwarding for your OS, sorry :(```
